data_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: kt98194.us-east4.gcp
      user: IsmaelRT
      password: Ismael01
      role: dbt_role
      database: dbt_db
      warehouse: dbt_wh
      schema: dbt_schema
      threads: 10
